
train:
  total_steps: 1000000
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008]
    learning_rate_steps: [1000000]
    total_steps: 1000000

postprocess:
  max_total_size: 150
  score_threshold: 0.0
