
train:
  total_steps: 1000000
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008]
    learning_rate_steps: [20000, 10000]

eval:
  eval_batch_size: 64

predict:
  predict_batch_size: 64
