
train:
  total_steps: 1000000
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008, 0.00008]
    learning_rate_steps: [20000, 50000, 100000]
    total_steps: 1000000

postprocess:
  max_total_size: 150
  score_threshold: 0.0

retinanet_parser:
  use_autoaugment: True
  autoaugment_policy_name: 'v1'
