
train:
  total_steps: 200000
  frozen_variable_prefix: 'disable_this'
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008]
    learning_rate_steps: [60000, 120000]

postprocess:
  max_total_size: 150
  score_threshold: 0

resnet:
  resnet_depth: 101


postprocess:
  max_total_size: 150
  score_threshold: 0.0
