
train:
  total_steps: 1000000
  frozen_variable_prefix: 'disable_this'
  learning_rate:
    init_learning_rate: 0.08
    learning_rate_levels: [0.008, 0.0008]
    learning_rate_steps: [60000, 120000]

architecture:
  multilevel_features: 'nasfpn'

resnet:
  resnet_depth: 200

nasfpn:
  fpn_feat_dims: 256
  min_level: 3
  max_level: 7
  num_repeats: 5
  use_separable_conv: False

retinanet_parser:
  aug_scale_min: 0.8
  aug_scale_max: 1.2
  output_size: [1024, 1024]
  max_num_instances: 200

postprocess:
  max_total_size: 150
  score_threshold: 0.0

