
train:
  total_steps: 200000
  learning_rate:
    type: 'cosine'
    init_learning_rate: 0.08
    total_steps: 30000
    warmup_learning_rate: 0.000001
    warmup_steps: 5000

architecture:
  multilevel_features: 'nasfpn'
  backbone: 'efficientnet-b7'

nasfpn:
  fpn_feat_dims: 256
  min_level: 3
  max_level: 7
  num_repeats: 5
  use_separable_conv: False

retinanet_parser:
  output_size: [600, 600]
  aug_scale_min: 0.8
  aug_scale_max: 1.2
  use_autoaugment: True
  autoaugment_policy_name: 'v3'
  max_num_instances: 200

postprocess:
  max_total_size: 200
  score_threshold: 0.0

