
train:
  total_steps: 200000
  learning_rate:
    type: 'cosine'
    init_learning_rate: 0.08
    total_steps: 10000
    warmup_learning_rate: 0.000001
    warmup_steps: 5000
  checkpoint:
    path: 'gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-10-14/model.ckpt-112602'
    prefix: 'resnet50/'

architecture:
  multilevel_features: 'nasfpn'

resnet:
  resnet_depth: 50

nasfpn:
  fpn_feat_dims: 300
  min_level: 3
  max_level: 7
  num_repeats: 5
  use_separable_conv: False
  dropblock:
    dropblock_keep_prob: 0.7
    dropblock_size: 3

retinanet_parser:
  aug_scale_min: 0.8
  aug_scale_max: 1.2
  use_autoaugment: True
  autoaugment_policy_name: 'v3'
  max_num_instances: 200

postprocess:
  max_total_size: 200
  score_threshold: 0.0
