
train:
  total_steps: 200000
  learning_rate:
    type: 'cosine'
    init_learning_rate: 0.08
    total_steps: 10000
    warmup_learning_rate: 0.000001
    warmup_steps: 5000
  checkpoint:
    path: 'gs://new_tpu_storage/pretrained/efficientnet-b5/model.ckpt'
    prefix: 'backbone/'
  frozen_variable_prefix: r'efficientnet-b\d\/blocks_([0-9]|1[0-4])\/conv2d'

architecture:
  multilevel_features: 'nasfpn'
  backbone: 'efficientnet-b5'

nasfpn:
  fpn_feat_dims: 256
  min_level: 3
  max_level: 7
  num_repeats: 5
  use_separable_conv: False

retinanet_parser:
  output_size: [640, 640]
  aug_scale_min: 0.8
  aug_scale_max: 1.2
  use_autoaugment: True
  autoaugment_policy_name: 'v3'
  max_num_instances: 200

postprocess:
  max_total_size: 200
  score_threshold: 0.0
